fix lfs

diff --git a/modules/src/Makefile.template-contrib b/modules/src/Makefile.template-contrib
--- a/modules/src/Makefile.template-contrib
+++ b/modules/src/Makefile.template-contrib
@@ -13,8 +13,16 @@ all: $(SUBDIR)
 
 $(SUBDIR):
 	$(H)tar -xzf $(TGZ)
-	$(H)if test ! "nodiff" = "$(DIFF)"; then cd $(SUBDIR); patch -p1 < ../$(DIFF) 1>/dev/null; if [ $$? != 0 ]; then echo " ! error patching !"; fi;  fi
-	$(H)cd $(SUBDIR);$(MAKE) -f Makefile PREFIX=$(PREFIX) TARGET=$(TARGET) CONFIG=$(CONFIG)
+	$(H)if test ! "nodiff" = "$(DIFF)"; then \
+		cd $(SUBDIR); \
+		patch -p1 < ../$(DIFF) 1>/dev/null; \
+		if [ $$? != 0 ]; then \
+			echo -e "\n ! error patching !\n";\
+		fi;\
+	fi
+	$(H)cd $(SUBDIR);\
+		$(MAKE) -f Makefile \
+			PREFIX=$(PREFIX) TARGET=$(TARGET) CONFIG=$(CONFIG)
 
 clean:
 	$(H)rm -rf $(SUBDIR)
